version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

matrix:
  allow_failures:
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"

init:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - pip install -U pip
  - pip install -r dev_requirements.txt
  - python setup.py bdist
  - python setup.py bdist_wheel
  - python setup.py sdist --formats=gztar,zip
  - pip install .

build: off

test_script:
  - python -m coverage run --branch --source . -m unittest discover --verbose

after_test:
  - python -m coverage report --show-missing
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")
